<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="FOCUS-QA-10" name="com.focus.testcases.CreditTest" tests="37" failures="3" timestamp="6 May 2022 11:44:19 GMT" time="1555.746" errors="0">
  <testcase name="checkSavedCreditLimitAuthorisation" time="18.882" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkSavingWithEnteringCreditDays" time="8.677" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkSaveCreditNoteVoucherWithSavedCustomerOrVendorAccount" time="30.919" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkLogin" time="13.881" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkSavingCreditLimitAuthorisationWithNameInput" time="13.196" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkSavePurchaseVoucherWithRMANumbersFromExcel" time="63.385" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkSaveSalesOrderWithPartialQntyConsumptionFromPVoucher" time="32.465" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkSaveSalesInvVatandConsumeQtyPartiallyFromPartiallyConsumedSalesOrder" time="68.304" classname="com.focus.testcases.CreditTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.CreditTest.checkSaveSalesInvVatandConsumeQtyPartiallyFromPartiallyConsumedSalesOrder(CreditTest.java:450)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkSaveSalesInvVatandConsumeQtyPartiallyFromPartiallyConsumedSalesOrder -->
  <testcase name="checkEnableOnlyARTagInPreferences" time="18.928" classname="com.focus.testcases.CreditTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.CreditTest.checkEnableOnlyARTagInPreferences(CreditTest.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkEnableOnlyARTagInPreferences -->
  <testcase name="checkDeleteOptionInCreditLimitAuthorisation" time="16.665" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkEditoptionInCreditLimit" time="9.321" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkSavePurchaseVoucherWithRmaFromNotePad" time="65.160" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkErasingAllDataAfterSavingSalesInvoiceVoucherWithRMAFromNotePad" time="53.381" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkSaveDebitNotesVoucherWithSavedCustOrVenAccount" time="28.786" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkcreditlimitAuthorisationHomeScreen" time="16.274" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkSavingCreditLimitAuthorisationWithVaildDataWithoutCreditDaysForApprovalInLevel1" time="17.746" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkResavingCreditLimitAuthorisation" time="35.545" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkSalesInvoiceVoucherWithCreatedCustOrVenAccount" time="63.943" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkErasingAllDataAfterExcel" time="53.291" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkSaveSalesInvoicesVoucherWithRMAFromExcel" time="85.336" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkValidateQuantityAndNetValuesInTheSalesOrderVoucherHomePage" time="13.819" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkSaveSalesInvoiceVoucherWithRmaFromNotePad" time="76.464" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkSalesOrderVoucherHomeandValidateQtyAndNetValues" time="13.470" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkSavePurchaseVoucherWithCreatedCustOrVenAccount" time="58.038" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkAddingQuantityAndNetFromTransactionFieldsInSalesOrderVoucher" time="79.183" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkSaveSalesOrderVoucher" time="32.621" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkCopyToClipandPasteBoardPreviouslySavedPurVoucherWithRmaAndSaveWithSameRma" time="64.589" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkSaveSalesInvoiceVatVoucherByConsumingPartialQuantity" time="61.707" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkSavePurchaseReturnsVoucherWithSavedCustOrVenAccount" time="96.745" classname="com.focus.testcases.CreditTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.CreditTest.checkSavePurchaseReturnsVoucherWithSavedCustOrVenAccount(CreditTest.java:264)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkSavePurchaseReturnsVoucherWithSavedCustOrVenAccount -->
  <testcase name="checkSavingCreditLimitAuthorisationWithOutInput" time="9.362" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkErasingAllTransactions" time="53.206" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkCopyToClipBoardFromSavedPurchaseVoucherWithRmaFromNotePad" time="66.462" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkSavePurchaseVoucherWithRMANumbersFromExcelAfterEraseAll" time="85.376" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkMappingDepartmentAndAccountInMapctreditLimitScreen" time="19.097" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkSaveCustomerOrVendorAccountForVouchers" time="21.812" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkSavePurchaseVoucher" time="85.283" classname="com.focus.testcases.CreditTest"/>
  <testcase name="checkSavedAccountInMastersList" time="4.427" classname="com.focus.testcases.CreditTest"/>
</testsuite> <!-- com.focus.testcases.CreditTest -->
